#!/bin/bash
node gluegen.js
node-waf configure
node-waf clean
node-waf

# Make sure o3node exists
if [ ! -d o3node ]; then
    mkdir o3node
fi

# Copy binaries
cp build/default/o3.node o3node/o3.node

# Copy modules
fs=`find modules -type f ! -name "*.h"`
for f in $fs
do
    g=`echo $f | sed 's/modules\(.*\)/o3node\1/g'`
    h=`echo $g | sed 's/\(.*\)\/.*/\1/g'`
    mkdir -pv $h
    cp -v $f $g
done

# Copy README
cp -v README_o3node o3node/README

# Run tests
node o3node/fastxml/test/test.js
node o3node/xml/test/test.js
