#!/bin/bash
echo "Building plugin."
xcodebuild > /dev/null 
echo "Copying scripts."
cp tools/osx/update_installer build/Release/npplugin.plugin/Contents/MacOS
cp tools/osx/md5 build/Release/npplugin.plugin/Contents/MacOS
