#!/bin/bash -e
cd `dirname $0`
cd ..

#lets copy some stuff
if [ $# -ne 3 ]
then
	echo "Usage: export <ajaxorg reponame> <modulename> <platform>"
	exit -1
fi

echo "exporting $2 to ajaxorg/$1 for platform $3 ...."

# lets check out the module
[ -d "export" ] || mkdir "export"
cd "export"
[ -d "$1" ] || git clone "git@github.com:ajaxorg/$1"
cd "$1"
git pull

mkdir lib || true
mkdir "lib/$1" || true
cp "../../modules/$2/index.js" "lib/$1/index.js"
cp -a "../../modules/$2/node/*" . || true
cp -a "../../modules/$2/test"  .|| true
cp -a "../../modules/$2/example" .|| true
cp "../../build/default/o3.node" "lib/$1/o3-$3.node" 
cp "../../modules/o3.js" "lib/$1/o3.js"

#run unittest
node test/test.js

git add * || true
git commit -m "Autobuild" || true
git push

echo "export done"
