#!/bin/bash -e
cd `dirname $0`
cd ..

#lets copy some stuff
if [ $# -ne 2 ]
then
	echo "Usage: export <modulename> <platform>"
	exit -1
fi

echo "exporting $1 to ajaxorg/node-o3-$1 for platform $2 ...."

# lets check out the module
[ -d "export" ] || mkdir "export"
cd "export"
[ -d "node-o3-$1" ] || git clone "git@github.com:ajaxorg/node-o3-$1"
cd "node-o3-$1"
git pull

mkdir lib || true
mkdir "lib/node-o3-$1" || true
cp "../../modules/$1/index.js" "lib/node-o3-$1/index.js"
cp -a "../../modules/$1/node/*" . || true
cp -a "../../modules/$1/test"  .|| true
cp -a "../../modules/$1/example" .|| true
cp "../../build/default/o3.node" "lib/node-o3-$1/o3-$2.node" 
cp "../../modules/o3.js" "lib/node-o3-$1/o3.js"

#run unittest
node test/test.js

git add * || true
git commit -m "Autobuild" || true
git push

echo "export done"
